---
# - hosts: localhost
#   become: yes

#   tasks:
#     - name: install pip3
#       apt: name=python3-pip state=present update-cache=yes 

#     - name: Install latest passlib with pip
#       pip: name=passlib  

#     - name: Install apache2-utils
#       apt: name=apache2-utils 

#     - name: "create directory for traefik"
#       file:
#         path: "/srv/docker/traefik/traefik"
#         state: directory
#         recurse: yes

#     - name: "deploying traefik config file"
#       template:
#         src: "docker/traefik/dynamic.yml"
#         dest: "/srv/docker/traefik/traefik/dynamic.yml"
#         force: yes


#     - name: Configure locale to 'en_US.UTF-'
#       command: localectl set-locale LANG=en_US.UTF-8

- hosts: localhost
  become: yes
  roles:
      - ../roles/docker-compose-systemd
  vars:
      docker_services:
      - name: dhis2
        enabled: yes
        need_restart: yes
        root_dir: /srv/docker/dhis2
        compose_template: docker/dhis2/docker-compose.yml
        env_template: docker/.env
        unit_template: docker-compose/compose-unit.j2
        
      - name: traefik
        enabled: yes
        need_restart: yes
        root_dir: /srv/docker/traefik
        compose_template: docker/traefik/docker-compose.yml
        env_template: docker/.env
        unit_template: docker-compose/compose-unit.j2

        


    